[package]
name = "kart-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "kart_rs"
path = "src/lib/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.1"
clap = { version = "4.0.18", features = ["derive"] }
dialoguer = "0.10.2"
image = "0.24.4"
image_hasher = "1.1.0"
lazy_static = "1.4.0"
rayon = "1.5.3"
uvc = { version = "0.2.0", features = ["vendor"] }
